// <auto-generated />
namespace DISANVANHOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class data4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(data4));
        
        string IMigrationMetadata.Id
        {
            get { return "202512121409470_data4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
